name: Build README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Configure pip caching
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build database
        run: python build_database.py
      - name: Update README
        run: |-
          python update_readme.py --rewrite
          cat README.md
      - name: Update subdir README's 
        run: |-
          python3 scripts/build_subdir_toc.py aws
          python3 scripts/build_subdir_toc.py celery
          python3 scripts/build_subdir_toc.py django
          python3 scripts/build_subdir_toc.py django-rest-framework
          python3 scripts/build_subdir_toc.py drf-yasg
          python3 scripts/build_subdir_toc.py fast-ai
          python3 scripts/build_subdir_toc.py git
          python3 scripts/build_subdir_toc.py github
          python3 scripts/build_subdir_toc.py google
          python3 scripts/build_subdir_toc.py home-office
          python3 scripts/build_subdir_toc.py htmx
          python3 scripts/build_subdir_toc.py javascript
          python3 scripts/build_subdir_toc.py kubernetes
          python3 scripts/build_subdir_toc.py mac
          python3 scripts/build_subdir_toc.py markdown
          python3 scripts/build_subdir_toc.py meilisearch
          python3 scripts/build_subdir_toc.py microsoft-dynamics
          python3 scripts/build_subdir_toc.py misc
          python3 scripts/build_subdir_toc.py pytest
          python3 scripts/build_subdir_toc.py python
          python3 scripts/build_subdir_toc.py r
          python3 scripts/build_subdir_toc.py slack
          python3 scripts/build_subdir_toc.py wagtail
      - name: Commit and push if anything changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated READMEs")
          git push
